/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Main: typeof import('./src/components/Main/Main.vue')['default']
    PlayerBar: typeof import('./src/components/PlayerBar/PlayerBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
